version: '3.7'
volumes:
  gems: {}
services:
    jekyll:
        image: jekyll/builder:3.8
        ports:
          - 4000:4000
        volumes:
         - .:/srv/jekyll
         - gems:/usr/local/bundle
        command: jekyll serve 